all:
	make clean
	make -f mkfile1
	make clean
	make -f mkfile2
	make clean
	make -f mkfile3
	make clean
	make -f mkfile4
	make clean
	make -f mkfile5
	make clean
	make -f mkfile6
	make clean
#rcs -i ....
#ci -l ....
#co -l ....
	make import1

clean:
	-rm -rf *.o
	-rm import1 import2 myapp
	-rm mylib.a

